version: '3'
services:
  python_app:
    volumes:
      - ${LOCAL_PATH}:/working/frc_tester/reports
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    command:
      python -u main.py